# Generated by Django 4.1 on 2022-09-19 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bili', '0003_exercise_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='owner_z',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
